### PR TITLE
Jbrowse 3.0

### PR DESCRIPTION
**Pull request by scottcain**

### CODE REVIEW

**Comment by nathandunn** [comment]
@scottcain  so far so good.  I removed a file.  Everything looks good so far.  Just testing it right now.

**Comment by scottcain** [comment]
Lovely; I didn't notice that there was one script named 'fetch-vcf.sh' and one named 'fetch_vcf.sh'.  Thanks for cleaning up.

**Comment by scottcain** [comment]
Also, I'll modify the jbrowse dockerfile to use this script--it's currently hard coded but the jbrowse and apollo dockerfiles should use the same tool for fetching these data.

**Comment by nathandunn** [comment]
tested it and it wasn't broken

**Pull request merged**
